using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    class Problem44
    {
        /// <summary>
        /// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
        ///1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
        ///It can be seen that P4 + P7 = 22 + 70 = 92 = P8.However, their difference, 70 − 22 = 48, is not pentagonal.
        ///Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
        ///D = | Pk − Pj| is minimised; what is the value of D?
        /// </summary>
        /// <param name="agrs"></param>
        static void Main(string[] agrs)
        {

            int result = 0;
            bool notFound = true;
            int i = 1;
            int k = 0;

            while (notFound)
            {
                i++;
                int n = i * (3 * i - 1) / 2;

                for (int j = i - 1; j > 0; j--)
                {
                    int m = j * (3 * j - 1) / 2;
                    if (isPentagonal(n - m) && isPentagonal(n + m))
                    {
                        result = n - m;
                        k = j;
                        notFound = false;
                        break;
                    }
                }
            }



            Console.WriteLine(result);
            Console.ReadKey();
        }

        static bool isPentagonal(int number)
        {
            double penTest = (Math.Sqrt(1 + 24 * number) + 1.0) / 6.0;
            return penTest == ((int)penTest);
        }



    }

}
