using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    class Problem45
    {
        /// <summary>
        /// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
        ///Triangle Tn = n(n + 1) / 2	 	1, 3, 6, 10, 15, ...
        ///Pentagonal Pn = n(3n−1) / 2	 	1, 5, 12, 22, 35, ...
        ///Hexagonal Hn = n(2n−1)	 	1, 6, 15, 28, 45, ...
        ///It can be verified that T285 = P165 = H143 = 40755.
        ///Find the next triangle number that is also pentagonal and hexagonal.
        /// </summary>
        /// <param name="args"></param>
        static void Main (string [] args)
        {


            long result = 0;
            int i = 143;

            while (true)
            {
                i++;
                result = i * (2 * i - 1);

                if (isPentagonal(result))
                {
                    break;
                }
            }

           
            Console.WriteLine(result);
            Console.ReadKey();
        }


        static bool isPentagonal(long number)
        {
            double penTest = (Math.Sqrt(1 + 24 * number) + 1.0) / 6.0;
            return penTest == ((int)penTest);
        }
    }
}
